### ISSUE TITLE
Scope of the challenge

### ISSUE THREAD

**Issue by filmaj** [classam/magnificent#1]
What exactly does "report on its status" mean?

- Is it supposed to check the status of the server, single-shot, and report back?
- Is it supposed to sample Magnificent at some specified frequency?

**Comment by classam** [comment]
I feel like we should clarify this as 

"We want to write a service to monitor the health of Magnificent Server externally. We want the service to run continuously, and check Magnificent Server at least once every 15 seconds. We want to know if it has thrown a non-200-OK response in the past minute, and we especially want to know if the service is no longer responding to requests. This service needs some method of outputting the status of Magnificent Server. "

Does that sound okay?

**Comment by classam** [comment]
I mean, writing a "pinger" is just 

    > curl -sL -w "%{http_code}" localhost:12345

from the command line
