### ISSUE TITLE
README overwritten with latest pull req

### ISSUE THREAD

**Issue by filmaj** [classam/magnificent#9]
ABORT! ROLLBACK! REVERT!

**Comment by AndrewBurian** [comment]
Maybe my bad?
I fixed it on the dev branch of my repo if you want to just pull that again.

https://github.com/andrewburian/magnificent dev

**Comment by cstyan** [comment]
I forgot to tell @AndrewBurian that we were actually merging the PR's.  Also, daemonized monitor, I like it.

**Comment by classam** [comment]
Derp. Fixed.
